Added popups
Dagic-zewdu/portifolio pull request #10
Opened 2022-01-25 14:13 UTC by Dagic-zewdu

Add popups for the project details. Now we can see the project detail in a popup and also the data in the popups are dynamic

2022-01-25 16:29 UTC, Meltrust requested changes
Hi @Dagic-zewdu, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Your project is beautiful and the logic is rock solid.  Please kindly read my comments below, implement the changes and your project should be approved really fast!!! 💪 


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

To highlight:

- Most of the project is rock solid!

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-01-25 16:29 UTC, Meltrust commented on index.html
> +        <!-- Modal -->
Your modal looks good and works well 💯.  However, it does not follow the Figma design closely enough:

Your modal:

![image](https://user-images.githubusercontent.com/57421823/151008741-8f1b89a0-514a-4cb7-b81a-48e4eb244b7a.png)

![image](https://user-images.githubusercontent.com/57421823/151012483-d4df0a44-7638-4f43-80d5-689bd8644f1f.png)

This is the Figma modal:

![image](https://user-images.githubusercontent.com/57421823/151012723-65bad042-c172-4530-8a2e-1343a9e7e616.png)


Please, kindly:

- [ ] Update the modal font stylings, so the sizes, weights, line-heights, etc matches the Figma.
- [ ] Update the modal main window so it has slightly rounded corners, like in the Figma.
- [ ] Update the modal main featured image, so it has also slight rounded corners, like in the Figma.
- [ ] The "See live" and "See source" buttons should be aligned horizontally like in the Figma template, not vertically, please kindly do so. 
- [ ] The line above the "See live" button, please make it semi-transparent and extend it so it spans about 90% of the modal, horizontally.  Please check the Figma to ensure this line looks the same. 💪 

_Note:  The example that is given in the project requirements, in which the modal buttons are aligned vertically, is just an example using template 5.  You are using template 1, which uses horizontal buttons as seen above._

If you implement this changes, your portfolio project modals will look striking!! 💪 💪

2022-01-25 16:29 UTC, Meltrust commented on index.js
> +const projects = [{
- [ ] Your modal is greatly implemented, however, according to the project requirements:

![image](https://user-images.githubusercontent.com/57421823/151015393-2368bdbc-0f28-46f4-9357-b17c3811e52d.png)

As seen above, all the projects section is created dynamically with the information from the projects array (all the HTML of the section is created when the page loads). This requires changes in existing code - already created HTML code for projects list should be removed and instead it should be added via JavaScript.

This means you can use the `projects` array and logic that you already have, to populate the projects section of the main page entirely with javascript!

If you are struggling or don't know how to do so, here is an [example](https://github.com/olawale-o/portfolio-mobile-version/pull/15/files#diff-0eb547304658805aad788d320f10bf1f292797b5e6d745a3bf617584da017051R95)

Please kindly do so, so adding a new project should be just a matter of adding a new element to the array! This will make your life a lot easier in the future! 💪

2022-01-26 08:15 UTC, moise10r approved these changes
<h1>Status: Approve  :champagne:  :+1: :confetti_ball: 

### **Hi @Team** , 

### **Congratulations! 🎉 Project Approved ✅**

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 



## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏💻  


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-01-26 08:15 UTC, moise10r commented on index.html
>  <body>
[[work section]()](https://github.com/Dagic-zewdu/portifolio/blob/93d47c3e2fe5e5b4b5bebc01f6f60cd12e89ac17/index.html#L86-L140)

- [ OPTIONAL] All those cards information should be stored into an array of objects then create a function to render through the array and create dynamically your HTML with the information from the object array as you did with the modal. the works section must stay empty

- I strongly suggest you make it so the cards are generated dynamically so in the future adding a new project will be just a matter of including in your projects array

2022-01-26 08:15 UTC, moise10r commented on index.html
> +        </div>
![Screenshot](https://user-images.githubusercontent.com/57562869/151124370-19d4d7a9-9ade-45f3-95dc-85dcf0c4e699.png)

- [OPTIONAL ] Kindly Add `background-color `to the left and right side of your images and make sure that the whole size image `width` is displayed correctly 

Figma: 

![fig](https://user-images.githubusercontent.com/57562869/151125509-3ba23570-eaee-462c-b18f-3aa1322c3a49.png)

2022-01-26 08:15 UTC, moise10r commented on index.html
>                      </a>
https://github.com/Dagic-zewdu/portifolio/blob/93d47c3e2fe5e5b4b5bebc01f6f60cd12e89ac17/index.html#L86-L88

![f](https://user-images.githubusercontent.com/57562869/151126316-249a19ed-5730-442c-b03f-61ac1af75c9e.png)


- [OPTIONAL ] The whole image `width and height` must be displayed correctly on the desktop version, Kindly fix that and make sure it display correctly before you merge this PR

2022-01-26 08:18 UTC, merged