Desktop media query added
Dagic-zewdu/portifolio pull request #4
Opened 2022-01-13 16:06 UTC by Dagic-zewdu

To make this project more responsive I added a media query for the desktop site.

2022-01-13 20:11 UTC, Whoistolu requested changes
Hello @Dagic-zewdu ,

You have done a great job so far!

There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️


_Check the inline comments under the review for sections to improve._

### Optional suggestions
Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.
### N/A

Cheers and Happy coding!

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2022-01-13 20:11 UTC, Whoistolu commented on index.html
> -        </section>
- [ ] [REQUIRED] For mobile: Kindly check the "About Myself" section, it seems to be off the design a bit, I guess this is as a result of you trying to implement the desktop version. You can check your padding and margin to the left.

Your Implementation   |  Figma Design
:-------------------------:|:-------------------------:
![your-design](https://user-images.githubusercontent.com/58692590/149396397-97dde501-b136-4809-87e5-0e08879fcf53.png) |  ![figma](https://user-images.githubusercontent.com/58692590/149396439-979f41a4-e2e6-44a5-92a0-a35c49b8c8d6.png)

2022-01-13 20:11 UTC, Whoistolu commented on index.html
> +                <img class="profile-image" src="images/Image_4.png" alt="image_4.png">
- [ ] [REQUIRED] Mobile design: It looks like this image source/link is broken, please check the link in order to fix it, and also, please fix this particular card. It is the second card for the work section, the image is supposed to be above the "Multi-Post Stories" text not below the `See Project` button.

### Your Implementation
![yor-design2](https://user-images.githubusercontent.com/58692590/149398385-e204e013-d819-4a27-809d-b4871d2a6d14.png) 
### Figma Design
![figma2](https://user-images.githubusercontent.com/58692590/149398415-caf6dc09-1b50-49ca-b8e6-8d89da8e216e.png)

2022-01-13 20:11 UTC, Whoistolu commented on index.html
> +                    <h2 class="card-title">Multi-Post Stories</h2>
- [ ] [REQUIRED] It will be nice to stick to the font, font size, and font-weight as much as possible in order to make your project look like the template provided.
Kindly take look at other texts for similar implementation. Thank you.

### Your Implementation 
![your-design3](https://user-images.githubusercontent.com/58692590/149399591-1598bdfb-2789-411f-b3b1-1bd56002cc0d.png) 
###  Figma Design
![figma3](https://user-images.githubusercontent.com/58692590/149399628-22e65df3-fba9-4a1a-b549-aa7da4c31059.png)

2022-01-13 20:11 UTC, Whoistolu commented on style.css
> +}
- [ ] [REQUIRED] You have done a great job by setting the minimum width of your screen to 992px, however, you have horizontal and vertical scroll bars. Please note that you are not supposed to have this. I inspected your design with the chrome dev tools and it seems way bigger. 
 I would recommend making the width 100% and don't fix it so your design can fit into different desktop screen sizes.. Well done 👍🏽 
![desktop](https://user-images.githubusercontent.com/58692590/149401748-2d74ab59-bd17-4e8c-be10-7917e00a9042.png)

2022-01-14 08:53 UTC, mmsesay approved these changes
Hi @Dagic-zewdu , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

- [ ] [OPTIONAL] Your application seems to have horizontal scrolling. I suggest you take a look at it.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-01-14 09:00 UTC, merged